name: caldera 
channels:
  - pytorch
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - alabaster=0.7.12=py37_0
  - appnope=0.1.0=py37_0
  - appscript=1.1.0=py37h1de35cc_0
  - asn1crypto=0.24.0=py37_0
  - astroid=2.2.5=py37_0
  - astropy=3.1.2=py37h1de35cc_0
  - atomicwrites=1.3.0=py37_1
  - babel=2.6.0=py37_0
  - backcall=0.1.0=py37_0
  - backports=1.0=py37_1
  - backports.os=0.1.1=py37_0
  - backports.shutil_get_terminal_size=1.0.0=py37_2
  - beautifulsoup4=4.7.1=py37_1
  - bitarray=0.8.3=py37h1de35cc_0
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - blosc=1.15.0=hd9629dc_0
  - boto=2.49.0=py37_0
  - bottleneck=1.2.1=py37h1d22016_1
  - bzip2=1.0.6=h1de35cc_5
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - cffi=1.12.2=py37hb5b8e2f_1
  - chardet=3.0.4=py37_1
  - click=7.0=py37_0
  - cloudpickle=0.8.0=py37_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.1=py37_0
  - conda=4.7.12=py37_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.6.0=py37h1de35cc_0
  - contextlib2=0.5.5=py37_0
  - cryptography=2.6.1=py37ha12b0ac_0
  - curl=7.64.0=ha441bb4_2
  - cython=0.29.6=py37h0a44026_0
  - cytoolz=0.9.0.1=py37h1de35cc_1
  - dask-core=1.1.4=py37_1
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.5.0=py37_1
  - docutils=0.14=py37_0
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py37_0
  - expat=2.2.6=h0a44026_0
  - fastcache=1.0.2=py37h1de35cc_2
  - filelock=3.0.10=py37_0
  - flask=1.0.2=py37_1
  - freetype=2.9.1=hb4e5f40_0
  - future=0.17.1=py37_0
  - get_terminal_size=1.0.0=h7520d66_0
  - gettext=0.19.8.1=h15daf44_3
  - gevent=1.4.0=py37h1de35cc_0
  - glib=2.56.2=hd9629dc_0
  - glob2=0.6=py37_1
  - gmp=6.1.2=hb37e062_1
  - gmpy2=2.0.8=py37h6ef4df4_2
  - greenlet=0.4.15=py37h1de35cc_0
  - h5py=2.9.0=py37h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.0=py37_2
  - html5lib=1.0.1=py37_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py37_0
  - imageio=2.5.0=py37_0
  - imagesize=1.1.0=py37_0
  - intel-openmp=2019.3=199
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.4.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - isort=4.3.16=py37_0
  - itsdangerous=1.1.0=py37_0
  - jbig=2.1=h4d881f8_0
  - jdcal=1.4=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=he5867d9_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - jupyterlab=0.35.4=py37hf63ae98_0
  - jupyterlab_server=0.2.0=py37_0
  - krb5=1.16.1=hddcf347_7
  - lazy-object-proxy=1.3.1=py37h1de35cc_2
  - libarchive=3.3.3=h786848e_5
  - libcurl=7.64.0=h051b688_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - liblief=0.9.0=h2a1bed3_2
  - libpng=1.6.36=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.8.0=ha12b0ac_4
  - libtiff=4.0.10=hcb84e12_2
  - libxml2=2.9.9=hab757c2_0
  - libxslt=1.1.33=h33a18ac_0
  - llvmlite=0.28.0=py37h8c7ce04_0
  - locket=0.2.0=py37_1
  - lxml=4.3.2=py37hef8c89e_0
  - lz4-c=1.8.1.2=h1de35cc_0
  - lzo=2.10=h362108e_2
  - markupsafe=1.1.1=py37h1de35cc_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.3=199
  - mkl-service=1.1.2=py37hfbe908c_5
  - mkl_fft=1.0.10=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.1=h3018a27_3
  - msgpack-python=0.6.1=py37h04f5b5a_1
  - multipledispatch=0.6.0=py37_0
  - navigator-updater=0.2.1=py37_0
  - nbconvert=5.4.1=py37_3
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - ninja=1.9.0=py37h04f5b5a_0
  - nltk=3.4=py37_1
  - nose=1.3.7=py37_2
  - notebook=5.7.8=py37_0
  - numba=0.43.1=py37h6440ff4_0
  - numexpr=2.6.9=py37h7413580_0
  - numpydoc=0.8.0=py37_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h1de35cc_3
  - packaging=19.0=py37_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.4=py37_0
  - partd=0.3.10=py37_1
  - path.py=11.5.0=py37_0
  - pathlib2=2.3.3=py37_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=h0a44026_0
  - pep8=1.7.1=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.4.1=py37hb68e598_0
  - pkginfo=1.5.0.1=py37_0
  - ply=3.11=py37_0
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - psutil=5.6.1=py37h1de35cc_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.0=py37_0
  - py-lief=0.9.0=py37h1413db1_2
  - pycodestyle=2.5.0=py37_0
  - pycosat=0.6.3=py37h1de35cc_0
  - pycparser=2.19=py37_0
  - pycrypto=2.6.1=py37h1de35cc_9
  - pycurl=7.43.0.2=py37ha12b0ac_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.3.1=py37_0
  - pylint=2.3.1=py37_0
  - pyodbc=4.0.26=py37h0a44026_0
  - pyopenssl=19.0.0=py37_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.14.11=py37h1de35cc_0
  - pysocks=1.6.8=py37_0
  - pytables=3.5.1=py37h5bccee9_0
  - pytest=4.3.1=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.5.0=py37_0
  - pytest-doctestplus=0.3.0=py37_0
  - pytest-openfiles=0.3.2=py37_0
  - pytest-remotedata=0.3.1=py37_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - python-libarchive-c=2.8=py37_6
  - python.app=2=py37_9
  - pywavelets=1.0.2=py37h1d22016_0
  - pyzmq=18.0.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=0.5.7=py37_1
  - qtconsole=4.4.3=py37_0
  - qtpy=1.7.0=py37_1
  - readline=7.0=h1de35cc_5
  - rope=0.12.0=py37_0
  - ruamel_yaml=0.15.46=py37h1de35cc_0
  - scikit-image=0.14.2=py37h0a44026_0
  - scikit-learn=0.20.3=py37h27c97d8_0
  - send2trash=1.5.0=py37_0
  - simplegeneric=0.8.1=py37_2
  - singledispatch=3.4.0.3=py37_0
  - sip=4.19.8=py37h0a44026_0
  - snappy=1.1.7=he62c110_3
  - snowballstemmer=1.2.1=py37_0
  - sortedcollections=1.1.2=py37_0
  - soupsieve=1.8=py37_0
  - sphinx=1.8.5=py37_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-websupport=1.1.0=py37_1
  - spyder=3.3.3=py37_0
  - spyder-kernels=0.4.2=py37_0
  - sqlite=3.30.0=ha441bb4_0
  - statsmodels=0.9.0=py37h1d22016_0
  - tblib=1.3.2=py37_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py37_0
  - torchvision=0.2.2=py_3
  - tornado=6.0.2=py37h1de35cc_0
  - traitlets=4.3.2=py37_0
  - unicodecsv=0.14.1=py37_0
  - unixodbc=2.3.7=h1de35cc_0
  - urllib3=1.24.1=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.14.1=py37_0
  - wheel=0.33.1=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - wrapt=1.11.1=py37h1de35cc_0
  - wurlitzer=1.0.2=py37_0
  - xlrd=1.2.0=py37_0
  - xlsxwriter=1.1.5=py37_0
  - xlwings=0.15.4=py37_0
  - xlwt=1.3.0=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zict=0.1.4=py37_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - agavepy==0.9.4
    - amqp==2.5.2
    - appdirs==1.4.3
    - aq==0.0.2
    - aqbt==0.0.1
    - aqseq==0.1.6
    - arrow==0.14.3
    - aspy-yaml==1.3.0
    - attrs==19.3.0
    - autodocsumm==0.1.13
    - autopep8==1.4.4
    - autoplanner==0.0.4a0
    - backports-ssl-match-hostname==3.7.0.1
    - bayesian-optimization==1.0.1
    - bcbio-gff==0.6.6
    - benchlingapi==2.1.11
    - billiard==3.6.1.0
    - bioadapter==0.0.2
    - biomart==0.9.2
    - biopython==1.74
    - black==18.9b0
    - bs4==0.0.1
    - cachecontrol==0.12.5
    - cachetools==3.1.1
    - cachy==0.3.0
    - celery==4.4.0
    - cfgv==2.0.1
    - checksumdir==1.1.7
    - cleo==0.7.6
    - click-completion==0.5.1
    - click-default-group==1.2.1
    - clikit==0.4.2
    - colorhash==1.0.2
    - colorlog==4.0.2
    - colour==0.1.5
    - commonmark==0.9.1
    - conda-pack==0.4.0
    - configparser==3.8.1
    - coverage==4.5.4
    - coveralls==1.8.2
    - crayons==0.2.0
    - cycler==0.10.0
    - daft==0.1.0
    - dash==1.0.0
    - dash-core-components==1.0.0
    - dash-html-components==1.0.0
    - dash-renderer==1.0.0
    - dash-table==4.0.0
    - dasi==0.1.1
    - depinfo==1.5.1
    - dictdiffer==0.8.0
    - dill==0.2.9
    - django==2.2.9
    - dnaplotlib==1.0
    - docformatter==1.3
    - docopt==0.6.2
    - edge-genome==2.2.0
    - fcsparser==0.2.0
    - fire==0.3.1
    - fish==1.1
    - flake8==3.7.9
    - flask-compress==1.4.0
    - flowcytometrytools==0.5.0
    - frozendict==1.2
    - gbgb==0.1.0
    - google-api-core==1.21.0
    - google-api-python-client==1.9.3
    - google-auth==1.18.0
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.4.1
    - googleapis-common-protos==1.52.0
    - hdmedians==0.13
    - httplib2==0.14.0
    - identify==1.4.7
    - ijson==2.4
    - importlib-metadata==1.1.3
    - importlib-resources==1.0.2
    - inflection==0.3.1
    - isodate==0.6.0
    - jdna==0.1.7
    - jellyfish==0.0.1
    - jsmin==2.2.2
    - jsonbinio==0.0.1a0
    - jsonlines==1.2.0
    - jsonschema==3.2.0
    - jupyter-http-over-ws==0.0.6
    - keats==0.2.29
    - keyring==20.0.1
    - kiwisolver==1.1.0
    - kombu==4.6.7
    - liccheck==0.4.2
    - linear-tsv==1.1.0
    - lobio==0.5.6
    - lockfile==0.12.2
    - loggable-jdv==0.1.7
    - marshmallow==3.2.1
    - matplotlib==3.1.1
    - mccabe==0.6.1
    - more-itertools==8.0.0
    - mpmath==1.1.0
    - msgpack==0.6.2
    - msgpack-numpy==0.4.4.3
    - mysession==0.0.1
    - natsort==6.0.0
    - nbopen==0.6
    - nest-asyncio==1.0.0
    - networkx==2.4
    - nodeenv==1.3.3
    - norgateparser==0.0.1
    - numpy==1.17.3
    - oauthlib==3.1.0
    - openpyxl==2.4.11
    - opt-einsum==3.2.1
    - owlready2==0.22
    - pandas==1.0.5
    - pastel==0.2.0
    - percy==2.0.2
    - petname==2.2
    - pexpect==4.7.0
    - pip==20.2
    - pipdeptree==0.13.2
    - pipenv==2018.11.26
    - plotly==3.10.0
    - pluggy==0.12.0
    - poetry==1.0.10
    - poetry-setup==0.3.6
    - pre-commit==1.20.0
    - primer3-py==0.6.0
    - primer3plus==1.0.8
    - protobuf==3.12.2
    - py-spy==0.3.0
    - pyasn1==0.4.7
    - pyasn1-modules==0.2.7
    - pyblastbio==0.8
    - pycallgraph==1.0.1
    - pycycle==0.0.8
    - pydash==4.7.4
    - pydent==1.0.2
    - pylev==1.3.0
    - pyparsing==2.4.2
    - pyro-api==0.1.2
    - pyro-ppl==1.3.1
    - pyrxn==-0.0.4-
    - pysbol==2.3.3.post6
    - pytest-mock==1.10.4
    - pytest-sugar==0.9.2
    - pytz==2019.3
    - pyyaml==5.1.1
    - randomcolor==0.4.4.5
    - rdflib==4.2.2
    - recommonmark==0.6.0
    - redis==3.2.1
    - requests==2.22.0
    - requests-oauthlib==1.2.0
    - requests-toolbelt==0.8.0
    - retry==0.9.2
    - retrying==1.3.3
    - rsa==4.0
    - rx==3.1.0
    - sbh-prospector==0.1
    - sbolsession==0.1.3
    - schedule==0.6.0
    - schemdraw==0.6.0
    - scikit-bio==0.5.5
    - scipy==1.3.1
    - sd2-dictionary-writer==0.0.0
    - seaborn==0.10.0
    - selenium==3.141.0
    - semantic-version==2.8.4
    - setuptools==41.4.0
    - shellingham==1.3.1
    - six==1.12.0
    - sortedcontainers==2.1.0
    - sparqlwrapper==1.8.4
    - sphinx-bootstrap-theme==0.7.1
    - sqlalchemy==1.3.11
    - sqlparse==0.3.0
    - statistics==1.0.3.5
    - supervisor==4.1.0
    - sympy==1.4
    - synbiohub-adapter==1.2
    - tenacity==5.1.1
    - termcolor==1.1.0
    - terrarium-capp==0.1.5
    - toml==0.10.0
    - tomlkit==0.5.11
    - torch==1.5.0
    - torch-scatter==2.0.4
    - tox==3.13.2
    - tox-conda==0.2.1
    - tqdm==4.35.0
    - trident==1.1
    - unidecode==1.1.1
    - untokenize==0.1.1
    - uritemplate==3.0.0
    - urlopen==1.0.0
    - uvloop==0.12.2
    - validator-py==1.3.0
    - validators==0.14.1
    - vine==1.3.0
    - virtualenv==16.5.0
    - virtualenv-clone==0.5.3
    - waitress==1.3.0
    - walrus==0.7.1
    - webcolors==1.9.1
    - websocket-client==0.53.0
    - xarray==0.12.3
    - yapf==0.28.0
    - yt==3.5.1
    - zipp==0.5.2
prefix: /Users/justinvrana/anaconda3

